-- Platform shared tables (reserved for future Infrastructure/Shared module entities)
-- Currently no platform-level tables are required by Infrastructure or Shared modules.
-- This placeholder ensures the Flyway baseline starts at V1 for clean-slate deployments.
