export const INFRA_COPY = {
  title: '基础设施管理',
  description: '集中管理平台基础设施能力、运行配置和治理数据。',
  nav: {
    dictionary: '字典',
    config: '配置',
    errorCodes: '错误码',
    cache: '缓存',
    audit: '审计',
    tenant: '租户',
    security: '安全',
    scheduler: '调度',
    i18n: 'i18n',
    dataI18n: '数据i18n',
    timezone: '时区',
    attachment: '附件',
    eventBus: '事件总线',
  },
  action: {
    create: '新建',
    edit: '编辑',
    save: '保存',
    cancel: '取消',
    search: '查询',
    reset: '重置',
    trigger: '手动触发',
    triggering: '触发中',
    delete: '删除',
  },
  state: {
    loading: '加载中',
    empty: '暂无数据',
    enabled: '启用',
    disabled: '停用',
    draft: '草稿',
  },
} as const
